import { Certification } from "@/types/journey";

export const useCertification = () => ({
  certificationData: [
    {
      id: "cert-azure-dev",
      type: "certification",
      title: "Microsoft Certified: Azure Developer Associate",
      issuer: "Microsoft",
      startDate: "Dec 2024",
      endDate: "Dec 2025",
      description: "Validated ability to design, build, test, and maintain cloud applications and services on Microsoft Azure using C# and the .NET stack.",
      tools: [
        "Azure Functions",
        "Azure Cosmos DB",
        "Azure API Management",
        "CI/CD",
        "Azure Key Vault",
        "Azure Logic Apps",
        "Azure SQL",
        "Cloud Security",
        "Cloud Storage",
        "Azure Service Bus",
        "Microservices",
      ],
      link: "https://www.credly.com/badges/a45b8aac-225e-6f26",
    },
    {
      id: "cert-azure-fundamentals",
      type: "certification",
      title: "Microsoft Certified: Azure Fundamentals",
      issuer: "Microsoft",
      startDate: "Jul 2024",
      description: "Demonstrated foundational knowledge of Azure cloud services, solutions, and governance—including pricing, compute, storage, and identity features.",
      tools: [
        ".NET Framework",
        "C#",
        "ASP.NET Core",
        "Microsoft Azure",
        "Unit Testing",
        "Azure DevOps Services",
        "API Design",
        "Microservices",
      ],
      link: "https://www.credly.com/badges/eeb9305c-7253-746e",
    },
    {
      id: "cert-adse",
      type: "certification",
      title: "Advanced Diploma in Software Engineering",
      issuer: "APTECH Computer Education",
      startDate: "Jun 2022",
      description: "Completed intensive software engineering training covering both frontend and backend development, system design, and software architecture.",
      tools: [
        "React.js",
        "Vue.js",
        "JavaScript",
        "TypeScript",
        "Responsive Web Design",
        "Front-End Development",
        "API Integration",
      ],
    },
  ] as Certification[],
});
